# Site Settings
baseurl: ""
url : "https://bonasfvck.github.io"

# Blog Settings
theme_settings :
  title : Bon
  favicon : assets/favicon.ico

  # Profile Settings
  profile :
    image : assets/img/smile.png
    username : Bon
    description : This is my journey to Cloud!
    experience :
      - start : 2014
        end : 2020
        experience : The A Company
    skills : 
      - skill : AWS
        value : 10  # Percent value
      - skill : Azure
        value : 15  # Percent value
      - skill : Sitecore
        value : 80  # Percent value
      - skill : Asp.Net MVC
        value : 85  # Percent value
        
  # Icons
  icons :
    email:  # Full email address, e.g. "sample@google.com"
    linkedin:  # Full URL 
    github: 
    gitlab: 
    bitbucket: 
    google_plus:
    twitter: bonasfvck
    youtube:
    facebook:
    instagram: bonasfvck

  # Disqus
  disqus_shortname :

# Pagination
paginate: 5
paginate_path: "page:num"

# Build Ssttings
sass:
  sass_dir: _sass
  style: :compressed
gems: [jekyll-paginate]
bootstrap:
  assets: true
