# Site Settings
baseurl: ""
url : "https://bonasfvck.github.io"

# Blog Settings
theme_settings :
  title : Bon
  favicon : assets/favicon.ico

  # Profile Settings
  profile :
    image : assets/img/frankestein.png
    username : Bon
    description : Hey! I am studying Cloud technologies, and this blog documents my journey. I'll be posting codes, Cloud techs and anything in bwtween. Get on board and we'll have healthy discussions in the comments box. Let's explore possibilities!
    experience :
      - start : 2014
        end : 2020
        experience : Application Developer at A Company
      - start : 2013
        end : 2014
        experience : Intern Developer at S Company
    skills : 
      - skill : AWS
        value : 10  # Percent value
      - skill : Azure
        value : 15  # Percent value
      - skill : Sitecore
        value : 80  # Percent value
      - skill : Asp.Net MVC
        value : 85  # Percent value
        
  # Icons
  icons :
    email:  # Full email address, e.g. "sample@google.com"
    linkedin:  # Full URL 
    github: 
    gitlab: 
    bitbucket: 
    google_plus:
    twitter: bonasfvck
    youtube:
    facebook:
    instagram: bonasfvck

  # Disqus
  disqus_shortname : bonasfvck

# Pagination
paginate: 5
paginate_path: "page:num"

# Build Ssttings
sass:
  sass_dir: _sass
  style: :compressed
gems: [jekyll-paginate]
bootstrap:
  assets: true
